
/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 6.0_1 */
public interface JmmTreeConstants {
  public int JJTPROGRAM = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTCLASSDECLARATION = 2;
  public int JJTVOID = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMETHODRETURN = 5;
  public int JJTMAINDECLARATION = 6;
  public int JJTMETHODDECLARATION = 7;
  public int JJTPRIMITIVE = 8;
  public int JJTIFSTATEMENT = 9;
  public int JJTELSESTATEMENT = 10;
  public int JJTASSIGNMENTSTATEMENT = 11;
  public int JJTARRAYASSIGN = 12;
  public int JJTWHILESTATEMENT = 13;
  public int JJTEXPRESSION = 14;
  public int JJTIDENTIFIER = 15;
  public int JJTINTEGER = 16;
  public int JJTBOOL = 17;
  public int JJTTHISREF = 18;
  public int JJTNOT = 19;
  public int JJTOPERATOR = 20;
  public int JJTAND = 21;
  public int JJTLESSTHAN = 22;
  public int JJTPLUS = 23;
  public int JJTMINUS = 24;
  public int JJTTIMES = 25;
  public int JJTDIVIDED = 26;
  public int JJTARRAYACCESS = 27;
  public int JJTFUNCTION = 28;
  public int JJTEXTENDS = 29;
  public int JJTNEWARRAY = 30;
  public int JJTNEWOBJECT = 31;
  public int JJTIDENTIFIERINSTRUCTION = 32;
  public int JJTSTATICDEC = 33;
  public int JJTMETHOD = 34;
  public int JJTMAINMETHOD = 35;
  public int JJTARGUMENTTYPE = 36;
  public int JJTIMPORTRETURN = 37;
  public int JJTARRAYDECLARATION = 38;
  public int JJTMEMBER = 39;
  public int JJTCLASSNAME = 40;
  public int JJTCLASSHEADER = 41;
  public int JJTCLASSBODY = 42;
  public int JJTPRIMITIVEDECLARATION = 43;
  public int JJTIMPORTDECLARATIONBODY = 44;
  public int JJTMEMBERIDENTIFIERTYPE = 45;
  public int JJTIDENTIFIERMEMBERDECLARATION = 46;
  public int JJTARGUMENTLIST = 47;
  public int JJTMETHODHEADER = 48;
  public int JJTMETHODBODY = 49;
  public int JJTARGUMENT = 50;
  public int JJTIMPORTFUNCTIONCALL = 51;
  public int JJTIMPORTFUNCTIONARGUMENTS = 52;
  public int JJTMETHODRETURNTYPE = 53;
  public int JJTMAINHEADER = 54;
  public int JJTMAINBODY = 55;
  public int JJTLENGTH = 56;
  public int JJTBRACKETEDEXPRESSION = 57;
  public int JJTTERMTAIL = 58;
  public int JJTIDENTIFIERTERM = 59;
  public int JJTPARAMETERLIST = 60;
  public int JJTPARAMETER = 61;
  public int JJTBLOCKSTATEMENT = 62;

  public String[] jjtNodeName = { "program", "ImportDeclaration", "ClassDeclaration", "Void", "VarDeclaration",
      "MethodReturn", "MainDeclaration", "MethodDeclaration", "Primitive", "IfStatement", "ElseStatement",
      "AssignmentStatement", "ArrayAssign", "WhileStatement", "Expression", "Identifier", "Integer", "Boolean",
      "ThisRef", "Not", "Operator", "And", "LessThan", "Plus", "Minus", "Times", "Divided", "ArrayAccess", "Function",
      "Extends", "NewArray", "NewObject", "IdentifierInstruction", "Static", "Method", "MainMethod", "ArgumentType",
      "ImportReturn", "ArrayDeclaration", "MemberDeclaration", "ClassName", "ClassHeader", "ClassBody",
      "PrimitiveDeclaration", "ImportDeclarationBody", "MemberIdentifierType", "IdentifierMemberDeclaration",
      "ArgumentList", "MethodHeader", "MethodBody", "Argument", "ImportFunctionCall", "ImportFunctionArguments",
      "MethodReturnType", "MainHeader", "MainBody", "Length", "BracketedExpression", "TermTail", "IdentifierTerm",
      "ParameterList", "Parameter", "BlockStatement" };
}
/*
 * JavaCC - OriginalChecksum=5150d56487a2fda3e49d8c2806584e53 (do not edit this
 * line)
 */
